/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLineMdCogFilledLoop: typeof import('~icons/line-md/cog-filled-loop')['default']
  const IconLineMdFileDocumentPlus: typeof import('~icons/line-md/file-document-plus')['default']
  const IconLineMdFileUpload: typeof import('~icons/line-md/file-upload')['default']
  const IconLineMdHeartFilled: typeof import('~icons/line-md/heart-filled')['default']
  const IconLineMdHeartHalfFilled: typeof import('~icons/line-md/heart-half-filled')['default']
  const IconLineMdLoadingAltLoop: typeof import('~icons/line-md/loading-alt-loop')['default']
  const IconMdiBlur: typeof import('~icons/mdi/blur')['default']
  const IconMdiDelete: typeof import('~icons/mdi/delete')['default']
  const IconMdiFileDocumentPlusOutline: typeof import('~icons/mdi/file-document-plus-outline')['default']
  const IconMdiLockQuestion: typeof import('~icons/mdi/lock-question')['default']
  const IconMdiMemory: typeof import('~icons/mdi/memory')['default']
  const IconMdiMenuOpen: typeof import('~icons/mdi/menu-open')['default']
  const IconMdiRename: typeof import('~icons/mdi/rename')['default']
  const IconMdiSend: typeof import('~icons/mdi/send')['default']
}
